# Generated by Django 4.2.11 on 2025-08-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
