# Generated by Django 4.2.11 on 2025-08-05 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_bookmark_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='url',
        ),
        migrations.CreateModel(
            name='BookmarkLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='bookmarks.bookmark')),
            ],
        ),
    ]
