#!/usr/bin/env python
"""
This file is automatically generated for the smartbookmarks project.
It provides Django's command-line utility for administrative tasks.

To use this project, you need to install Django and the required
dependencies (see requirements.txt). Once installed, you can run

    python manage.py migrate
    python manage.py runserver

to apply migrations and start the development server.
"""
import os
import sys

def main() -> None:
    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'smartbookmarks.settings')
    try:
        from django.core.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? "
            "Did you forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)


if __name__ == '__main__':
    main()